# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a1d7d9fa6b15c5b7a0e6fde79ddd022eb40a2a7dae8ae6d0218609682301658331e3375b0e7fd2f7197bdb8561aaf8c6b4bcaf51d989152e9ac16f72230ddae

test:
  secret_key_base: 9641eb2ec30779fe595bb511f369b0cfc5d191ac530e404305bb5aa3323cac13e88ef49f31a113a1fafbceb4d43dd85c0b9f4c71d73d4fc0ade8453b8aa2885f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
